[build]
  command = 'npm run build'
  environment = {NODE_VERSION = '18'}
  publish = 'dist'

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
  command = "yarn dev" # Command to start your dev server
  port = 5173
  publish = "dist" # Folder with the static content for _redirect file
  targetPort = 5252

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
