[build]
  command = 'node set-env.js && npm run build'
  environment = {NODE_VERSION = '18'}
  publish = 'dist'
  functions = 'netlify/functions'

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
  command = "yarn client" # Command to start your dev server
  publish = "dist" # Folder with the static content for _redirect file

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
